Repository AstarVienna/irdb, pull requests merged in 2024-02, with the labels that each got.

#153 Update of the MICADO detector file for quantum efficiency
  MICADO/MICADO_H4RG.yaml
  MICADO/QE_detector_H4RG.dat
Labels: instrument-specific, data update

#155 Several fixes in preparation of the CainMap
  Armazones/tests/__init__.py
  METIS/docs/example_notebooks/Introduction_to_Scopesim_for_METIS.ipynb
  METIS/docs/example_notebooks/LSS-YSO_model_simulation.ipynb
  METIS/docs/example_notebooks/LSS_AGN-01_preparation.ipynb
  METIS/docs/example_notebooks/LSS_AGN-02_simulation.ipynb
  METIS/docs/example_notebooks/RawHeaders.ipynb
  METIS/docs/example_notebooks/demos/demo_auto_exposure.ipynb
  METIS/docs/example_notebooks/demos/demo_detector_modes.ipynb
  METIS/docs/example_notebooks/demos/demo_grating_efficiency.ipynb
  MICADO/test_micado/test_micado_compiles.py
  OSIRIS/tests/test_maat_daves_tests.py
  OSIRIS/tests/test_maat_traces.py
Labels: documentation

#158 Remove support for Python 3.8
  .github/workflows/tests.yml
  irdb/badges.py
  irdb/publish_utils.py
Labels: irdb functionality

#150 Disble SourceDescriptionFitsKeywords for MICADO
  MICADO/MICADO_H4RG.yaml
Labels: instrument-specific
